---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key | default(omit) }}"
      api_key_id: "{{ api_key_id | default(omit)  }}"
      api_uri: "https://intersight.com/api/v1"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: present
    org_name: "default"
  tasks:
  # Get Org Info
  - name: "Get Organization Info"
    intersight_rest_api:
      <<: *api_info
      resource_path: /organization/Organizations
      query_params:
        $filter: "Name eq '{{ org_name }}'"
    register: org_info

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: org_info.api_response.Moid

  - name: Create Multicast Policy
    cisco.intersight.intersight_rest_api:
      <<: *api_info
      resource_path: "/ntp/Policies"
      api_body: {
        "Organization": {
            "ObjectType": "organization.Organization",
            "Moid": "{{ org_info.api_response.Moid }}"
        },
        "Name": "pyreq_demo",
        "Description": "Demo NTP Policy",
        "Enabled": True,
        "NtpServers": [
            "8.8.8.8",
            "8.8.4.4"
        ],
        "Timezone": "America/Los_Angeles",
        "Tags": []
      }
